In [17]:
import xgboost as xgb
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn

In [2]:
full_results = pd.read_csv('full_results.csv')
full_stats = pd.read_csv('FullKenPom_pt.csv')

print(full_results.shape)
print(full_stats.shape)

(1112, 11)
(1129, 27)

In [3]:
full_stats.head()

,Unnamed: 0,Season,TeamName,Tempo,AdjTempo,OE,AdjOE,DE,AdjDE,AdjEM,...,O_TO_Pct,D_TO_Pct,D-O_TO_Pct,O_OR_Pct,D_OR_Pct,O-D_OR_Pct,O_FT_Rate,D_FT_Rate,O-D_FT_Rate,LastTenRecord
0,0,2002,Duke,77.0734,73.9016,116.373,121.374,90.2544,87.3522,34.0220,...,18.5699,25.6865,7.1166,34.4605,34.0618,0.3987,41.0140,32.1378,8.8762,0.8
1,1,2002,Cincinnati,68.4368,66.9485,112.274,117.448,86.3924,86.6033,30.8442,...,17.1142,21.2481,4.1339,37.7143,31.3235,6.3908,40.5118,30.3685,10.1433,0.9
2,2,2002,Kansas,79.0371,77.6019,114.544,118.100,94.4261,90.3113,27.7883,...,20.4253,20.6425,0.2172,41.2084,32.5214,8.6870,35.2239,29.4168,5.8071,0.9
3,3,2002,Maryland,75.2758,73.3263,113.167,118.151,94.3706,91.2974,26.8534,...,18.3287,20.5133,2.1846,36.0518,33.5535,2.4983,41.5036,30.9028,10.6008,0.9
4,4,2002,Florida,71.8971,69.5612,110.418,115.387,91.1250,89.6694,25.7176,...,20.5232,25.2218,4.6986,38.4960,33.1315,5.3645,36.1769,34.5721,1.6048,0.6

In [4]:
full_results.head()

,Unnamed: 0,Year,Round,Region Number,Region Name,SeedA,ScoreA,TeamA,TeamB,ScoreB,SeedB
0,0,2002,0,0,First Four,16,77,Alcorn St,Siena,81,16
1,1,2002,1,1,South,1,84,Duke,Winthrop,37,16
2,2,2002,1,1,South,2,86,Alabama,Florida Atlantic,78,15
3,3,2002,1,1,South,3,71,Pittsburgh,Central Connecticut St,54,14
4,4,2002,1,1,South,4,89,USC,UNC Wilmington,93,13

In [5]:
###mask test and train data###
res_test_mask = (full_results['Year'] == 2016) | (full_results['Year'] == 2017) | (full_results['Year'] == 2018)
stats_test_mask = (full_stats['Season'] == 2016) | (full_stats['Season'] == 2017) | (full_stats['Season'] == 2018)
res_train_mask = (full_results['Year'] < 2016)
stats_train_mask = (full_stats['Season'] < 2016)

res_data_test = full_results[res_test_mask]
stats_data_test = full_stats[stats_test_mask]
res_data_train = full_results[res_train_mask]
stats_data_train = full_stats[stats_train_mask]

#reindex all of them
res_data_test = res_data_test.reset_index()
stats_data_test = stats_data_test.reset_index()
res_data_train = res_data_train.reset_index()
stats_data_train = stats_data_train.reset_index()

for i in range(len(res_data_test)):
    if res_data_test['Region Name'][i] == "First Four":
        res_data_test = res_data_test.drop(i)
for i in range(len(res_data_train)):
    if res_data_train['Region Name'][i] == "First Four":
        res_data_train = res_data_train.drop(i)
        
#reindex all of them
res_data_test = res_data_test.reset_index()
stats_data_test = stats_data_test.reset_index()
res_data_train = res_data_train.reset_index()
stats_data_train = stats_data_train.reset_index()

res_data_train.head()

#res_data_test.tail()
#stats_data_test.tail()
#res_data_train.tail()
#stats_data_train.tail()

,level_0,index,Unnamed: 0,Year,Round,Region Number,Region Name,SeedA,ScoreA,TeamA,TeamB,ScoreB,SeedB
0,1,1,1,2002,1,1,South,1,84,Duke,Winthrop,37,16
1,2,2,2,2002,1,1,South,2,86,Alabama,Florida Atlantic,78,15
2,3,3,3,2002,1,1,South,3,71,Pittsburgh,Central Connecticut St,54,14
3,4,4,4,2002,1,1,South,4,89,USC,UNC Wilmington,93,13
4,5,5,5,2002,1,1,South,5,75,Indiana,Utah,56,12

In [6]:
#these names match the kenpom stats csv
stats_vec = ["AdjTempo",
            "AdjOE",
            "AdjDE", # FLIP!!!
            "AdjEM",
            "seed",
            "ConfTournament",
            "SOSAdjEM",
            "NCSOSAdjEM",
            "O-D_eFG_Pct",
            "D-O_TO_Pct",
            "O-D_OR_Pct",
            "O-D_FT_Rate",
            "LastTenRecord"]

print(len(stats_vec))

13

In [7]:
# Move training data into 2 numpy arrays - data and labels (results)
N = len(res_data_train)

training_data = np.zeros((N,13))
training_labels = np.zeros((N,1))

for i in range(len(res_data_train)):
    year = res_data_train['Year'][i]
    teamA = res_data_train['TeamA'][i]
    teamB = res_data_train['TeamB'][i]
    score_diff = res_data_train['ScoreA'][i] - res_data_train['ScoreB'][i]
    for k in range(len(stats_data_train)):
        if ((stats_data_train['Season'][k] == year) and (stats_data_train['TeamName'][k] == teamA)):
            indexA = k
            break
            
    for k in range(len(stats_data_train)):
        if ((stats_data_train['Season'][k] == year) and (stats_data_train['TeamName'][k] == teamB)):
            indexB = k
            break
    for s in range(len(stats_vec)):
        stat = stats_vec[s]
        training_data[i][s] = stats_data_train[stat][indexA] - stats_data_train[stat][indexB]
    
    if (score_diff > 0):
        training_labels[i][0] = 1
    else:
        training_labels[i][0] = 0

In [8]:
# Move testing data into 2 numpy arrays - data and labels (results)
N = len(res_data_test)

testing_data = np.zeros((N,13))
testing_labels = np.zeros((N,1))

for i in range(len(res_data_test)):
#for i in range(5):
    year = res_data_test['Year'][i]
    teamA = res_data_test['TeamA'][i]
    teamB = res_data_test['TeamB'][i]
    score_diff = res_data_test['ScoreA'][i] - res_data_test['ScoreB'][i]
    for k in range(len(stats_data_test)):
        if ((stats_data_test['Season'][k] == year) and (stats_data_test['TeamName'][k] == teamA)):
            indexA = k
            break
            
    for k in range(len(stats_data_test)):
        if ((stats_data_test['Season'][k] == year) and (stats_data_test['TeamName'][k] == teamB)):
            indexB = k
            break
    for s in range(len(stats_vec)):
        stat = stats_vec[s]
        testing_data[i][s] = stats_data_test[stat][indexA] - stats_data_test[stat][indexB]
    
    if (score_diff > 0):
        testing_labels[i][0] = 1
    else:
        testing_labels[i][0] = 0

In [9]:
print(training_data.shape)
print(training_labels.shape)
print('\n')
print(testing_data.shape)
print(testing_labels.shape)

(882, 13)
(882, 1)


(189, 13)
(189, 1)

In [20]:
#Time to normalize the data
print( training_data )
print( training_data[:,0] )

[[  8.2874  24.2208 -14.8448 ...  -3.8099   9.5825   0.    ]
 [ -2.0491  15.7256  -7.3805 ...   3.1176  14.1589  -0.1   ]
 [ -0.3923  11.692   -6.6079 ...   0.1097  -7.4804  -0.1   ]
 ...
 [ -3.8929   5.545    9.4537 ...   0.729    1.6018  -0.1   ]
 [  2.7961   8.28    -0.1067 ...  -0.832   22.0564   0.2   ]
 [  7.5601  -2.562    1.6549 ...  -2.7993   2.0688   0.    ]]
[ 8.28740e+00 -2.04910e+00 -3.92300e-01  6.37470e+00  2.93070e+00
  1.28820e+00  1.51240e+00  1.42120e+00  2.68690e+00 -1.35780e+00
  8.05780e+00  1.54360e+00 -1.57500e-01 -1.06760e+00  1.50290e+00
  2.81560e+00  7.28200e+00  1.42900e-01  3.51100e-01 -5.55000e-01
 -5.00600e+00 -1.24620e+00  4.25890e+00 -5.77940e+00  1.55452e+01
  2.19120e+00  2.01850e+00 -1.06940e+00  2.61540e+00 -1.73600e-01
 -3.03420e+00  2.46020e+00  5.75700e+00  3.61800e+00 -3.13790e+00
  1.72110e+00 -8.19000e-02 -5.81900e-01  2.16710e+00 -2.29660e+00
  1.03152e+01  1.75010e+00 -1.79270e+00 -1.94620e+00  8.04910e+00
  1.11700e+00 -1.15570e+00  1.74500e+00  9.12370e+00 -8.73300e-01
 -1.67950e+00 -5.36770e+00  5.69020e+00 -2.02980e+00  8.91110e+00
  1.70600e+00  5.85800e-01 -2.85150e+00  4.36060e+00  7.04250e+00
  1.08050e+00  4.27560e+00  8.54840e+00  5.89000e-01 -2.79930e+00
  3.25000e-01 -3.08580e+00 -4.45520e+00 -1.12050e+00 -1.56820e+00
  9.15720e+00  8.71530e+00  1.14191e+01  3.92980e+00  6.93000e-01
 -1.98500e+00 -3.50010e+00  1.46710e+00 -8.74700e-01  1.38850e+00
 -1.89310e+00 -2.41680e+00 -5.32130e+00  5.44550e+00  7.41050e+00
 -6.27350e+00 -1.63230e+00 -9.05560e+00 -7.48950e+00  2.30180e+00
  8.18050e+00  6.33650e+00  3.26320e+00 -2.33210e+00  9.62800e-01
  5.61460e+00  8.16400e-01 -8.24300e-01 -5.56600e+00  5.77320e+00
  5.78780e+00 -8.26900e-01 -9.92300e-01 -1.35700e-01  1.64000e+00
 -3.58360e+00 -5.61980e+00 -3.46240e+00  8.97700e-01  3.94690e+00
  1.36314e+01  5.72430e+00 -8.80500e-01  3.78310e+00  1.56340e+00
 -2.06500e+00  8.16870e+00  3.89870e+00  3.72330e+00  1.86900e+00
  3.65400e-01  5.44240e+00 -7.83580e+00  6.96830e+00 -1.47860e+00
  2.12900e+00 -4.68160e+00 -2.75180e+00  4.56660e+00  4.84660e+00
  1.30750e+00  3.89090e+00 -4.28600e+00  2.93100e+00 -7.52200e-01
  1.18530e+00 -3.21670e+00  5.93430e+00  8.34400e-01 -2.41010e+00
  1.57400e+00 -2.92310e+00  6.10260e+00  1.77880e+00  8.41180e+00
 -6.46970e+00 -5.13420e+00  1.91009e+01 -3.55630e+00 -7.36240e+00
 -4.37990e+00  4.12460e+00 -6.80400e+00  2.70890e+00 -2.81200e-01
 -2.15000e-01  9.75300e-01 -7.21300e-01 -4.26560e+00 -1.86960e+00
  6.68160e+00  5.53300e+00 -3.61800e-01 -1.80760e+00 -9.59500e-01
  5.27400e+00  1.45830e+00  3.85550e+00 -5.94440e+00  2.86920e+00
 -4.99200e-01  5.09170e+00 -2.85580e+00  5.14760e+00 -1.23190e+00
  1.26280e+00 -3.79410e+00  6.39600e+00  3.38710e+00  1.04340e+00
  1.21960e+00  2.74320e+00  3.66800e-01  8.81900e-01  3.49200e+00
  3.48420e+00 -3.93920e+00 -8.48000e-01 -1.35630e+00 -3.83110e+00
  6.34180e+00  7.59130e+00 -3.49660e+00 -5.97570e+00 -4.20420e+00
 -1.60490e+00  1.04340e+00  3.71400e+00  1.01760e+00  4.15350e+00
 -2.67400e-01 -1.63100e+00  1.38500e-01  6.46600e-01 -2.63200e-01
  8.19340e+00  1.06906e+01  3.11830e+00 -8.70800e-01  1.70760e+00
 -1.83900e+00  7.58390e+00  8.45900e-01  9.04070e+00  1.13520e+00
 -4.90410e+00  1.11570e+00 -2.90700e-01 -6.95550e+00  2.03800e-01
 -1.38270e+00 -9.43200e-01  3.32130e+00 -1.56580e+00 -4.60920e+00
  8.26740e+00  4.86630e+00 -2.35630e+00 -1.65080e+00  6.97770e+00
  7.91680e+00 -3.74300e-01 -2.37910e+00  1.70000e-02 -1.27310e+00
  5.75620e+00  7.46600e-01 -4.05600e+00 -2.52260e+00  4.40480e+00
  5.62350e+00  6.47910e+00  1.82900e-01  2.90100e+00  8.17590e+00
 -4.12820e+00  3.64760e+00  1.07533e+01  1.47940e+00 -2.63330e+00
  7.98380e+00  8.83810e+00  5.16280e+00 -6.19700e-01 -2.64690e+00
 -1.96910e+00  5.31830e+00  1.58930e+00 -2.27710e+00  8.89570e+00
  4.51820e+00 -7.42510e+00  4.83100e-01 -1.60810e+00 -1.02540e+00
  2.88800e-01  4.55810e+00  3.99610e+00  4.38840e+00  7.25040e+00
  7.05920e+00  7.44310e+00  1.02675e+01  1.50280e+00 -3.11050e+00
 -4.67350e+00  1.63000e+00 -7.45700e-01  1.64310e+00 -1.11420e+00
 -3.24000e-01 -5.44420e+00 -1.56950e+00  2.63080e+00 -1.69610e+00
 -4.71600e-01 -5.44200e+00  4.26350e+00  9.37100e+00 -1.88890e+00
 -3.09900e-01 -4.67460e+00  4.39900e+00  9.25400e+00  7.75300e+00
 -9.64080e+00 -1.49240e+00  7.25280e+00 -1.11900e-01 -4.40370e+00
  2.59550e+00  1.73500e+00  1.99230e+00 -4.45130e+00 -2.95020e+00
 -2.97900e-01  4.50670e+00  9.38950e+00 -3.56320e+00  9.88300e+00
  5.85650e+00 -1.06480e+00 -5.91050e+00  4.72710e+00 -5.74490e+00
 -4.26720e+00 -4.23100e+00  7.67020e+00 -2.11000e-01 -7.35810e+00
  8.84070e+00 -2.28600e+00  1.66150e+00  5.45000e-01 -1.74680e+00
 -7.84700e-01 -1.33050e+00  1.64000e+00 -9.69700e-01 -2.15480e+00
  2.18700e-01  1.12393e+01 -6.35230e+00 -6.43680e+00 -2.41220e+00
  7.23000e-01 -2.33900e-01 -4.44300e-01  7.25220e+00  1.39290e+00
 -6.35800e-01 -3.94860e+00  4.22060e+00  4.55600e-01 -1.76580e+00
  3.50210e+00  1.44250e+00 -1.23680e+00 -1.44990e+00  4.50840e+00
  1.29833e+01  2.32400e+00 -1.40350e+00 -3.35330e+00 -2.78380e+00
  1.17030e+01 -4.69180e+00 -6.58460e+00  3.55300e-01 -1.52070e+00
  2.33610e+00  1.42900e-01 -3.31310e+00  6.80590e+00  8.15900e-01
  7.66730e+00  1.72990e+00  5.28050e+00 -7.06630e+00 -6.81930e+00
  4.39580e+00 -6.26100e-01  5.04110e+00  1.27486e+01 -3.81350e+00
  1.88940e+00  5.08680e+00 -6.99500e-01  6.68820e+00  9.98670e+00
 -5.52550e+00 -3.18590e+00  7.99350e+00 -9.95500e-01 -5.49880e+00
 -6.02300e-01  1.07550e+00 -3.21640e+00 -1.00451e+01  9.91000e-01
  1.71600e-01 -4.61210e+00 -8.95000e-01 -1.03280e+00 -3.18300e-01
 -1.90300e+00 -4.49150e+00  4.44500e-01 -2.23000e-01  4.39730e+00
 -6.98300e-01  9.08400e-01  7.85600e-01  2.86180e+00 -1.21260e+00
  4.16860e+00 -4.65260e+00 -3.56130e+00  2.61700e-01  5.85630e+00
  5.69550e+00  1.09886e+01  2.12130e+00 -1.11672e+01  3.75580e+00
 -6.22290e+00 -8.33160e+00  5.21500e-01  1.88450e+00 -1.65000e+00
 -3.54840e+00  4.01000e-01  1.61220e+00  7.87670e+00 -2.88090e+00
  4.10890e+00  1.41304e+01  4.89540e+00 -3.57500e-01 -5.19970e+00
  4.97470e+00  3.29400e-01 -3.36710e+00 -1.96400e-01  7.23040e+00
  7.74000e-01  4.62950e+00  2.78300e-01 -5.06450e+00 -4.53520e+00
  8.56700e-01  2.42050e+00  5.57400e-01 -4.90900e-01  9.18200e+00
  3.77800e-01 -6.33400e-01  1.86580e+00 -8.24060e+00 -3.10630e+00
 -6.74160e+00  4.85760e+00  5.02210e+00  5.16130e+00  7.67600e+00
 -3.60400e-01  5.27280e+00 -4.03110e+00 -1.07850e+00  7.05610e+00
  8.89400e-01  6.99810e+00 -8.50400e-01  1.10760e+00  1.79850e+00
  4.05920e+00  1.45990e+00  7.51650e+00  1.92830e+00 -2.44870e+00
 -4.30960e+00  5.26470e+00  3.51140e+00 -3.23210e+00  3.07790e+00
  2.58680e+00  4.96800e-01  2.40370e+00 -1.00310e+00  2.65990e+00
  6.47890e+00 -4.37530e+00  6.48300e-01  2.36620e+00  6.86850e+00
  6.97430e+00  4.18380e+00  1.06155e+01  2.13820e+00  3.32740e+00
 -4.64100e-01  2.86500e-01 -5.27450e+00 -5.27900e-01 -1.32420e+00
  6.02520e+00 -2.92160e+00  1.00780e+00 -4.27160e+00 -2.06610e+00
  6.17100e+00 -3.72900e-01  5.60870e+00  6.49480e+00 -1.77440e+00
 -2.05260e+00 -3.09860e+00 -2.72730e+00 -4.59420e+00  4.73360e+00
 -1.75040e+00  7.33610e+00  2.79300e+00  2.38820e+00 -8.23970e+00
  2.92220e+00 -4.23070e+00  3.47700e+00  7.36400e+00  2.18390e+00
  1.48830e+00 -5.83710e+00  5.50650e+00 -4.47900e+00 -3.46710e+00
 -9.44970e+00 -1.40820e+00  2.70050e+00 -1.48000e-02  5.45380e+00
 -4.67130e+00 -2.88030e+00  4.59280e+00 -1.30500e-01 -4.26330e+00
  1.20280e+00  8.08090e+00 -3.93190e+00 -5.24900e-01  2.60370e+00
  1.61660e+00 -1.42290e+00 -8.53770e+00 -2.32930e+00 -8.77000e-01
 -6.29580e+00 -4.15020e+00 -4.78350e+00 -2.15730e+00  4.80560e+00
  1.55750e+00  1.46410e+00  6.94460e+00 -3.64540e+00  5.44790e+00
  6.37100e-01  4.14860e+00 -9.02500e+00 -5.15600e-01 -2.34120e+00
 -2.14780e+00  6.25800e+00  5.27690e+00  9.38500e-01 -2.27760e+00
  2.64980e+00  1.72070e+00 -2.63030e+00 -2.61000e+00 -3.79400e-01
  2.58150e+00 -1.28410e+00 -1.89490e+00  6.58600e+00 -5.50300e-01
  2.55960e+00 -4.23940e+00  3.96000e-01 -5.74830e+00 -2.32160e+00
 -7.94190e+00  4.90330e+00 -4.41640e+00  5.91750e+00 -2.84450e+00
  1.78550e+00  3.14810e+00  3.72010e+00 -2.19530e+00 -6.09600e+00
  1.63790e+00 -5.53400e+00 -1.85180e+00  6.86520e+00 -1.18745e+01
  3.94360e+00 -2.98300e-01  5.39400e-01  2.95260e+00 -6.20300e-01
 -1.61200e-01 -1.71900e+00  3.19760e+00  7.16660e+00 -1.89810e+00
  2.13190e+00  2.94700e-01  3.68750e+00 -4.13750e+00  4.23700e-01
 -6.78000e-01 -1.51030e+00 -2.97870e+00  3.68520e+00 -9.89500e+00
 -1.52220e+00  3.83720e+00  3.55980e+00 -2.52000e+00  5.82020e+00
  1.54150e+00 -6.88440e+00 -7.76650e+00  4.66230e+00 -1.67200e-01
  3.00840e+00 -1.19960e+00 -5.33400e-01 -2.19830e+00  1.62320e+00
 -2.81750e+00 -1.40870e+00  4.76800e-01 -3.05860e+00  7.89800e-01
  3.57640e+00 -6.38230e+00  2.85570e+00 -8.89230e+00 -1.29750e+00
 -2.47110e+00 -7.08100e-01 -4.87500e-01  1.20080e+00  5.10740e+00
  5.56080e+00 -3.58690e+00  3.12140e+00  3.64050e+00 -6.50530e+00
  4.24780e+00 -2.23300e+00  1.12130e+00  2.72780e+00  8.69590e+00
 -4.39000e-01 -5.10760e+00 -6.01990e+00  7.34620e+00 -1.27590e+00
 -1.33200e+00  3.98020e+00 -1.03860e+00 -1.10180e+00  5.94100e-01
  1.74470e+00  2.60220e+00 -2.57660e+00  4.90240e+00  9.17800e-01
 -1.67120e+00  1.36010e+00  4.12900e+00 -6.94610e+00  4.52580e+00
  2.27310e+00 -4.74590e+00 -7.66040e+00 -1.95840e+00 -1.12960e+00
 -2.08890e+00  5.69530e+00  7.10300e+00  3.83000e+00  4.42700e+00
 -4.07700e-01 -7.24500e-01  2.50040e+00 -1.59780e+00  4.03720e+00
 -1.90780e+00  2.27400e-01 -1.89360e+00  4.83600e-01  4.92830e+00
 -1.16090e+00 -1.19100e-01 -1.74020e+00  5.05980e+00  8.31200e-01
 -2.51340e+00 -3.14600e-01 -6.42360e+00  6.44600e-01 -3.37520e+00
 -8.78140e+00 -3.60000e-01 -7.96750e+00 -4.26950e+00  1.70080e+00
 -6.70580e+00 -1.07220e+01  8.76100e-01  1.13970e+00  6.30030e+00
  1.85900e-01  3.11070e+00  3.20460e+00 -2.96600e-01 -4.68800e-01
  8.32700e-01  3.17630e+00  1.56700e+00  1.23100e+00  1.05390e+00
  2.29620e+00  2.98200e+00 -5.20310e+00 -4.01350e+00  5.68000e-02
 -5.27880e+00  2.45860e+00  4.39850e+00 -3.25210e+00 -1.82320e+00
 -4.43000e-01 -2.89410e+00  5.73800e-01 -2.95850e+00  2.50600e-01
 -1.25830e+00 -1.80240e+00  3.49120e+00 -1.94920e+00 -2.68400e+00
  2.67420e+00 -5.96960e+00  3.07850e+00 -1.53140e+00 -7.85700e-01
 -1.58200e-01 -2.18010e+00  1.78000e-01  2.87480e+00 -2.41200e-01
  2.42080e+00 -1.66600e-01  2.28480e+00 -5.50580e+00  1.54100e+00
  7.60410e+00  1.64200e-01 -5.29300e-01  2.37250e+00 -6.24520e+00
 -1.06000e-01  7.77150e+00 -6.16000e+00 -2.84890e+00  6.13460e+00
 -1.03290e+00  2.05260e+00 -8.42000e-02  2.87250e+00 -4.95670e+00
 -2.55590e+00  6.94850e+00 -3.54930e+00 -3.36190e+00 -2.43780e+00
  4.71540e+00  7.90600e-01  8.97700e-01 -5.31500e-01  8.48200e-01
  8.27680e+00 -3.99400e-01  9.58300e-01 -1.17260e+00  1.61970e+00
 -4.13570e+00  6.93780e+00 -8.20930e+00  2.48490e+00  1.05350e+00
  2.71600e-01 -1.44280e+00 -5.04490e+00  2.75500e+00 -2.13000e-01
 -1.05180e+00 -5.66510e+00 -1.89600e+00  1.91590e+00 -7.09500e+00
  1.39180e+00 -4.74410e+00  7.07310e+00  3.12100e-01  1.61650e+00
  2.87450e+00 -4.89000e-01 -2.32730e+00  9.90500e-01  3.52300e-01
 -3.07520e+00 -1.85450e+00 -1.85840e+00 -1.21720e+00 -6.66500e+00
  3.68750e+00  2.29500e-01  1.55180e+00 -4.72900e-01  1.31630e+00
 -4.59350e+00 -4.78330e+00 -5.59500e+00  2.68290e+00 -1.30030e+00
  7.88620e+00  8.59220e+00 -4.76800e-01  1.33460e+00  3.40900e+00
  1.12420e+00 -9.03740e+00  6.25020e+00  1.42310e+00 -6.34000e-01
  1.55090e+00 -8.15600e-01 -5.25030e+00  5.95300e-01  3.94660e+00
  4.90830e+00 -4.20220e+00 -4.84420e+00 -2.65110e+00 -3.21240e+00
 -6.24780e+00  2.75970e+00  5.20700e+00  2.44300e-01 -4.22790e+00
 -8.04280e+00  4.24000e-01  2.59690e+00 -1.11400e-01 -1.16000e-02
 -5.30750e+00  3.67140e+00  6.78660e+00  5.69030e+00  9.02900e-01
  1.09100e+00  3.36590e+00 -6.00970e+00  1.83040e+00 -1.09465e+01
  4.22900e-01  9.54300e-01  4.14540e+00  5.24450e+00 -1.28520e+00
 -1.31550e+00 -7.51760e+00  1.95990e+00  1.42850e+00 -3.89290e+00
  2.79610e+00  7.56010e+00]

In [39]:
test1 = sklearn.preprocessing.normalize( training_data, norm='max', copy=True )
print( test1.shape )
print( test1 )

# DOESNT WORK YET!!!!!!!!!!!!!!!!!!!!!!!!
test1[:2] = test1[:2] * -1

print( test1 )

(882, 13)
[[ 0.21213849  0.61999709 -0.37999293 ... -0.09752473  0.24529008
   0.        ]
 [-0.08868482  0.68060221 -0.31942722 ...  0.13492938  0.61279561
  -0.00432799]
 [-0.02143726  0.63891004 -0.36108909 ...  0.00599456 -0.4087669
  -0.00546451]
 ...
 [-0.41178586  0.58654284  1.         ...  0.07711266  0.16943631
  -0.01057787]
 [ 0.12677046  0.37540124 -0.0048376  ... -0.03772148  1.
   0.00906766]
 [ 1.         -0.33888441  0.21889922 ... -0.37027288  0.27364717
   0.        ]]
[[-0.21213849 -0.61999709  0.37999293 ...  0.09752473 -0.24529008
  -0.        ]
 [ 0.08868482 -0.68060221  0.31942722 ... -0.13492938 -0.61279561
   0.00432799]
 [-0.02143726  0.63891004 -0.36108909 ...  0.00599456 -0.4087669
  -0.00546451]
 ...
 [-0.41178586  0.58654284  1.         ...  0.07711266  0.16943631
  -0.01057787]
 [ 0.12677046  0.37540124 -0.0048376  ... -0.03772148  1.
   0.00906766]
 [ 1.         -0.33888441  0.21889922 ... -0.37027288  0.27364717
   0.        ]]

In [35]:
train_labels1 = training_labels
train_data1 = test1

training_matrix = xgb.DMatrix( train_data1, label=train_labels1 )
test_matrix = xgb.DMatrix( train_data1, label=train_labels1 )

evallist = [(test_matrix, 'eval'), (training_matrix, 'train')]

In [37]:
bst = xgb.train(param, training_matrix, 10, evallist)

AttributeError: 'DMatrix' object has no attribute 'shape'